"""Make the portable paper bibliography without repository audit-note fields."""
from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
source = HERE.parent / "references" / "references.bib"
if not source.exists():
    raise SystemExit("Build from the repository or the complete source package.")
text = source.read_text()
# Notes in the canonical bibliography document the evidence audit. Keep that
# archive intact while excluding those internal annotations from the paper.
while match := re.search(r"\bnote\s*=\s*\{", text):
    end = match.end()
    depth = 1
    while depth:
        if end >= len(text):
            raise ValueError("Unbalanced bibliography note")
        char = text[end]
        if char == "{" and text[end - 1] != "\\":
            depth += 1
        elif char == "}" and text[end - 1] != "\\":
            depth -= 1
        end += 1
    if end < len(text) and text[end] == ",":
        end += 1
    text = text[:match.start()] + text[end:]
text = re.sub(r",\s*\n\s*}", "\n}", text)
(HERE / "references.bib").write_text(
    "% Generated by prepare_bibliography.py from the canonical bibliography.\n"
    "% Audit-only note fields are intentionally omitted.\n" + text
)
